"""
Project: PitchAura
File Created: 2026-02-23
Author: Xingnan Zhu
File Name: space_creation.py
Description:
    Off-ball space creation metric.
    Measures the area a player commands (via Voronoi or pitch control) and
    how it changes over time, providing a continuous signal of the space
    generated by that player's off-ball movement within a time window.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from pitch_aura.space.voronoi import VoronoiModel
from pitch_aura.types import FrameSequence, PitchSpec


def space_creation(
    frames: FrameSequence,
    *,
    player_id: str,
    time_window: float = 5.0,
    control_model: object | None = None,
    pitch: PitchSpec | None = None,
) -> pd.DataFrame:
    """Measure the space created by a player's off-ball movement.

    For each frame in *frames* (optionally filtered to *time_window* seconds
    after the first frame), computes the area the player controls via Voronoi
    tessellation.  If *control_model* is provided it must expose a
    ``control(frame) -> VoronoiResult``-compatible interface and is used
    instead of the default :class:`~pitch_aura.space.voronoi.VoronoiModel`.

    Parameters:
        frames:        Tracking data (may span any length).
        player_id:     ID of the player to analyse.
        time_window:   Duration of the analysis window in seconds.  Frames
                       beyond ``first_timestamp + time_window`` are dropped.
        control_model: Optional custom spatial model.  Must have a
                       ``control(frame)`` method returning an object with an
                       ``areas`` dict keyed by player_id.  Defaults to
                       :class:`~pitch_aura.space.voronoi.VoronoiModel`.
        pitch:         Pitch specification.  Inferred from *frames* if omitted.

    Returns:
        DataFrame with columns:

        * ``timestamp`` — frame timestamp (s).
        * ``area_m2``   — area controlled by the player in that frame (m²).
        * ``delta_area``— change in controlled area vs. the previous frame
          (m²).  ``NaN`` for the first frame.

    Raises:
        ValueError: If *player_id* is not found in any frame of the sequence.
    """
    if not frames.frames:
        return pd.DataFrame(columns=["timestamp", "area_m2", "delta_area"])

    # Validate player exists in at least one frame
    all_pids = {pid for f in frames.frames for pid in f.player_ids}
    if player_id not in all_pids:
        raise ValueError(f"player_id {player_id!r} not found in any frame")

    # Apply time window
    t0 = frames.frames[0].timestamp
    t_end = t0 + time_window
    window_frames = [f for f in frames.frames if f.timestamp <= t_end]

    if not window_frames:
        return pd.DataFrame(columns=["timestamp", "area_m2", "delta_area"])

    # Resolve model and pitch
    resolved_pitch = pitch if pitch is not None else frames.pitch
    if control_model is None:
        model: object = VoronoiModel(pitch=resolved_pitch)
    else:
        model = control_model

    timestamps: list[float] = []
    areas: list[float] = []

    for frame in window_frames:
        if player_id not in frame.player_ids:
            continue
        result = model.control(frame)  # type: ignore[union-attr]
        area = result.areas.get(player_id, 0.0)
        timestamps.append(frame.timestamp)
        areas.append(area)

    if not timestamps:
        return pd.DataFrame(columns=["timestamp", "area_m2", "delta_area"])

    area_arr = np.array(areas)
    delta = np.empty(len(area_arr))
    delta[0] = np.nan
    delta[1:] = np.diff(area_arr)

    return pd.DataFrame({
        "timestamp": timestamps,
        "area_m2": area_arr,
        "delta_area": delta,
    })
